stages:
  - test
  - deploy

.python:
  image: python:3.8-slim-buster

.modules:
  before_script:
    - echo $BQ_SERVICE_ACCOUNT_JSON > svcaccount.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/svcaccount.json
    - pip3 install poetry
    - poetry config http-basic.bueno $NEXUS_USERNAME $NEXUS_PASSWORD
    - poetry config virtualenvs.in-project true
    - poetry install -vv
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/

Unit:
  stage: test
  extends:
    - .python
    - .modules
  script:
    - poetry run pytest --pspec tests/migration/unit
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-test-281401'

Integration:
  stage: test
  extends:
    - .python
    - .modules
  script:
    - poetry run pytest --pspec tests/migration/integration -s
  variables:
    MIGRATIONS_DIRECTORY: 'tests/migration/integration/mgrtns'
    GOOGLE_CLOUD_PROJECT: 'au-test-281401'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'

Staging:
  stage: deploy
  extends:
    - .python
    - .modules
  script:
    - poetry run migrate
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-staging'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'

Production:
  stage: deploy
  only: ["master"]
  when: manual
  extends:
    - .python
    - .modules
  script:
    - poetry run migrate
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-production'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'
