stages:
  - test
  - deploy

.python:
  image: python:3.8-slim-buster

.modules:
  before_script:
    - echo $BQ_SERVICE_ACCOUNT_JSON > svcaccount.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/svcaccount.json
    - pip3 install poetry
    - poetry config http-basic.bueno $NEXUS_USERNAME $NEXUS_PASSWORD
    - poetry config virtualenvs.in-project true
    - poetry install -vv
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/

test:
  stage: test
  extends:
    - .python
    - .modules
  script:
    - poetry run pytest --pspec tests/
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-staging'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'

staging:
  stage: deploy
  extends:
    - .python
    - .modules
  script:
    - poetry run migrate
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-staging'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'

production:
  stage: deploy
  only: ["master"]
  when: manual
  extends:
    - .python
    - .modules
  script:
    - poetry run migrate
  variables:
    GOOGLE_CLOUD_PROJECT: 'au-production'
    GOOGLE_CLOUD_LOCATION: 'australia-southeast1'
